
import { Property, FinancialRecord, Owner, SecurityLog, MaintenanceTask, BlogPost, LocalGuideTrip, StaffProfile, PropertyExpense, UtilityBill, Booking, Guest } from './types';

export const MOCK_GUESTS: Guest[] = [
    {
        id: 'G001',
        name: 'John Smith',
        email: 'john.smith@email.com',
        phone: '+1 555-0123',
        photo: 'https://i.pravatar.cc/150?img=12',
        verified: true,
        emailVerified: true,
        phoneVerified: true,
        idVerified: true,
        rating: 4.9,
        reviewCount: 12,
        bookingCount: 15,
        memberSince: '2022-03-15',
        languages: ['English', 'Spanish'],
        bio: 'Travel enthusiast and digital nomad. Love exploring new cultures!',
        location: 'New York, USA'
    },
    {
        id: 'G002',
        name: 'Maria Garcia',
        email: 'maria.garcia@email.com',
        phone: '+34 612-345-678',
        photo: 'https://i.pravatar.cc/150?img=45',
        verified: true,
        emailVerified: true,
        phoneVerified: true,
        idVerified: false,
        rating: 4.7,
        reviewCount: 8,
        bookingCount: 10,
        memberSince: '2023-01-20',
        languages: ['Spanish', 'English'],
        bio: 'Family traveler looking for authentic experiences.',
        location: 'Barcelona, Spain'
    },
    {
        id: 'G003',
        name: 'Hans Mueller',
        email: 'hans.mueller@email.com',
        phone: '+41 79-123-4567',
        photo: 'https://i.pravatar.cc/150?img=33',
        verified: true,
        emailVerified: true,
        phoneVerified: true,
        idVerified: true,
        rating: 5.0,
        reviewCount: 20,
        bookingCount: 25,
        memberSince: '2021-06-10',
        languages: ['German', 'English', 'French'],
        bio: 'Swiss businessman, frequent traveler to Albania.',
        location: 'Zurich, Switzerland'
    }
];

export const MOCK_BOOKINGS: Booking[] = [
    {
        id: 'BK001',
        propertyId: '1',
        guestId: 'G001',
        checkIn: '2024-09-15',
        checkOut: '2024-09-22',
        guests: 4,
        adults: 2,
        children: 2,
        totalPrice: 1386,
        nightlyRate: 180,
        cleaningFee: 85,
        serviceFee: 61,
        status: 'Confirmed',
        paymentStatus: 'Paid',
        specialRequests: 'Early check-in if possible, traveling with kids',
        createdAt: '2024-08-01T10:30:00Z'
    },
    {
        id: 'BK002',
        propertyId: '2',
        guestId: 'G002',
        checkIn: '2024-08-25',
        checkOut: '2024-08-30',
        guests: 2,
        adults: 2,
        children: 0,
        totalPrice: 625,
        nightlyRate: 120,
        cleaningFee: 45,
        serviceFee: 20,
        status: 'Checked-in',
        paymentStatus: 'Paid',
        createdAt: '2024-07-15T14:20:00Z'
    },
    {
        id: 'BK003',
        propertyId: '1',
        guestId: 'G003',
        checkIn: '2024-10-01',
        checkOut: '2024-10-08',
        guests: 2,
        adults: 2,
        children: 0,
        totalPrice: 1386,
        nightlyRate: 180,
        cleaningFee: 85,
        serviceFee: 61,
        status: 'Pending',
        paymentStatus: 'Pending',
        specialRequests: 'Need workspace with good WiFi',
        createdAt: '2024-08-20T09:15:00Z'
    },
    {
        id: 'BK004',
        propertyId: '3',
        guestId: 'G001',
        checkIn: '2024-07-10',
        checkOut: '2024-07-17',
        guests: 6,
        adults: 4,
        children: 2,
        totalPrice: 1050,
        nightlyRate: 140,
        cleaningFee: 70,
        serviceFee: 40,
        status: 'Checked-out',
        paymentStatus: 'Paid',
        createdAt: '2024-06-01T16:45:00Z'
    }
];
